export enum CityEnum {
  SAO_VICENTE = 'SAO_VICENTE',
  SANTOS = 'SANTOS',
  PRAIA_GRANDE = 'PRAIA_GRANDE',
  GUARUJA = 'GUARUJA',
  PERUIBE = 'PERUIBE',
  BERTIOGA = 'BERTIOGA',
  CUBATAO = 'CUBATAO',
  ITANHAEM = 'ITANHAEM',
  MONGAGUA = 'MONGAGUA'
}
