
export enum CollectionsEnum {
  SHORT_ESTABLISHMENTS = "SHORT_ESTABLISHMENTS",
  SHORT_PARKINGS = "SHORT_PARKINGS",
  RGS_APP_INFO = "RGS_APP_INFO",
  PLACES = 'PLACES',
  SUGGESTIONS_BAIXADA_SANTISTA = 'SUGGESTIONS_BAIXADA_SANTISTA',
  USERS = 'USERS',
  PEOPLE = 'PEOPLE'
}
